### ISSUE TITLE
Kérdések

### ISSUE THREAD

**Issue by acsadam0404** [acsadam0404/kuru#48]
1. Cikk kódja miért módosítható? (Én ennek példájára csináltam meg a kategória módosítást szóval ott is módosítható a kód) Ha javítani kell, akkor mindkét helyen szükséges!

2. Nagyon kis mennyiség esetén mint a kosár rosszul szumol-na.

3. Számla képernyőn az új tétel felvitelnél, mintha nem csak az active cikkek jönnének.

4. Feltöltésnél biztos jó az hogy úgy csináltuk meg tegnap előtt este, hogy egyből feltolja a képet még a mentés előtt?

5. Mi legyen olyankor, ha van egy cikk ami logikailag törölve lett, azaz db-ben ott van csak nem active állapotban. És egy olyan kódú/nevű cikket szeretnék felvenni, ami egy ilyen inaktiv. Jelenleg erre azt mondja nem lehet, mert létezik ilyen. Ami vagy jó vagy sem :)

6. Induláskor felkell venni az articlecategory táblában egy DUMMY kódú elemet. Fontos hogy ez legyen a kód, mert erre szűrők (articlecategoryserviceimpl)

7. Szükséges alapból a valuesetben quantity kulccsal felvenni elemet, mert megdöglik az új cikk felvitel (ez amúgy is kötelező mező, tehát ez lehet feleslegesen is irtam fel)

8. Kicsit fura ez a valueset, ami itt van (SI-ben sokkal szimpibb) :D

+1 Nagyjából ennyit találtam. Igyekeztem részletesen tesztelni, de mindenre biztos hogy nem gondoltam.

**Comment by acsadam0404** [comment]
1. Ne legyen módosítható.

**Comment by tmester** [comment]
3. nézd meg

**Comment by tmester** [comment]
4. ez jó így, de amikor feltöltöttük adjunk neki egy uid-et. UUID.randomUUID().toString()

**Comment by tmester** [comment]
5. legyen a cikk kód unique, db szintent. Teszteld le, hogy így jó -e.

**Comment by tmester** [comment]
- 6. legyen egy initial dump, mindig arról telepítünk. Ebbe ne legyen semmi tesztadat, csak ami kell.

**Comment by tmester** [comment]
- 7. tudom, hogy szar de jó az falura

**Comment by tmester** [comment]
- 7. ugyanaz mint 6

**Comment by tmester** [comment]
Logikai törlés miatt az 5.-nél nem lehet db tábla szinten unique a kód!
